apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params: 
  - name: url
    value: https://github.com/kameshsampath/pipeline-helloworld
  - name: revision
    value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: helloworld-image
spec:
  type: image
  params: 
  - name: url
    value: "dev.local/example/helloworld"
    # if you are on OpenShift uncomment the line below
    #value: "image-registry.openshift-image-registry.svc:5000/tutorial/helloworld"
